# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moony_mainwindow.ui'
#
# Created: Tue Dec 21 16:12:43 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 493)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(530, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/moon.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.picLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picLabel.sizePolicy().hasHeightForWidth())
        self.picLabel.setSizePolicy(sizePolicy)
        self.picLabel.setText("")
        self.picLabel.setPixmap(QtGui.QPixmap(":/images/images/moonypic.png"))
        self.picLabel.setScaledContents(True)
        self.picLabel.setObjectName("picLabel")
        self.horizontalLayout_2.addWidget(self.picLabel)
        self.fsfeaturesgroupBox = QtGui.QGroupBox(self.centralwidget)
        self.fsfeaturesgroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fsfeaturesgroupBox.sizePolicy().hasHeightForWidth())
        self.fsfeaturesgroupBox.setSizePolicy(sizePolicy)
        self.fsfeaturesgroupBox.setMinimumSize(QtCore.QSize(306, 344))
        self.fsfeaturesgroupBox.setObjectName("fsfeaturesgroupBox")
        self.layoutWidget = QtGui.QWidget(self.fsfeaturesgroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 30, 285, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fsLabel = QtGui.QLabel(self.layoutWidget)
        self.fsLabel.setObjectName("fsLabel")
        self.horizontalLayout.addWidget(self.fsLabel)
        self.fstypeLabel = QtGui.QLabel(self.layoutWidget)
        self.fstypeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fstypeLabel.setObjectName("fstypeLabel")
        self.horizontalLayout.addWidget(self.fstypeLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feat1Label = QtGui.QLabel(self.layoutWidget)
        self.feat1Label.setEnabled(True)
        self.feat1Label.setObjectName("feat1Label")
        self.verticalLayout_3.addWidget(self.feat1Label)
        self.feat2Label = QtGui.QLabel(self.layoutWidget)
        self.feat2Label.setEnabled(True)
        self.feat2Label.setObjectName("feat2Label")
        self.verticalLayout_3.addWidget(self.feat2Label)
        self.feat3Label = QtGui.QLabel(self.layoutWidget)
        self.feat3Label.setEnabled(True)
        self.feat3Label.setObjectName("feat3Label")
        self.verticalLayout_3.addWidget(self.feat3Label)
        self.feat4Label = QtGui.QLabel(self.layoutWidget)
        self.feat4Label.setEnabled(True)
        self.feat4Label.setObjectName("feat4Label")
        self.verticalLayout_3.addWidget(self.feat4Label)
        self.feat5Label = QtGui.QLabel(self.layoutWidget)
        self.feat5Label.setEnabled(True)
        self.feat5Label.setObjectName("feat5Label")
        self.verticalLayout_3.addWidget(self.feat5Label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.feat1LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.feat1LineEdit.setEnabled(True)
        self.feat1LineEdit.setObjectName("feat1LineEdit")
        self.verticalLayout.addWidget(self.feat1LineEdit)
        self.feat2LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.feat2LineEdit.setEnabled(True)
        self.feat2LineEdit.setObjectName("feat2LineEdit")
        self.verticalLayout.addWidget(self.feat2LineEdit)
        self.feat3LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.feat3LineEdit.setEnabled(True)
        self.feat3LineEdit.setObjectName("feat3LineEdit")
        self.verticalLayout.addWidget(self.feat3LineEdit)
        self.feat4LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.feat4LineEdit.setEnabled(True)
        self.feat4LineEdit.setObjectName("feat4LineEdit")
        self.verticalLayout.addWidget(self.feat4LineEdit)
        self.feat5LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.feat5LineEdit.setEnabled(True)
        self.feat5LineEdit.setObjectName("feat5LineEdit")
        self.verticalLayout.addWidget(self.feat5LineEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.fsfeaturesgroupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filesystemLabel = QtGui.QLabel(self.centralwidget)
        self.filesystemLabel.setObjectName("filesystemLabel")
        self.horizontalLayout_3.addWidget(self.filesystemLabel)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_Formatting = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Formatting.setIcon(icon1)
        self.actionStart_Formatting.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionStart_Formatting.setObjectName("actionStart_Formatting")
        self.actionStop_Formatting = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Formatting.setIcon(icon2)
        self.actionStop_Formatting.setObjectName("actionStop_Formatting")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.action_About_Moony_Creator = QtGui.QAction(MainWindow)
        self.action_About_Moony_Creator.setIcon(icon)
        self.action_About_Moony_Creator.setObjectName("action_About_Moony_Creator")
        self.action_Help = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help.setIcon(icon4)
        self.action_Help.setObjectName("action_Help")
        self.menuFile.addAction(self.actionStart_Formatting)
        self.menuFile.addAction(self.actionStop_Formatting)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.action_About_Moony_Creator)
        self.menuHelp.addAction(self.action_Help)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Moony Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.fsfeaturesgroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "File System Features:", None, QtGui.QApplication.UnicodeUTF8))
        self.fsLabel.setText(QtGui.QApplication.translate("MainWindow", "File System Selected:", None, QtGui.QApplication.UnicodeUTF8))
        self.fstypeLabel.setText(QtGui.QApplication.translate("MainWindow", "vfat", None, QtGui.QApplication.UnicodeUTF8))
        self.feat1Label.setText(QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.feat2Label.setText(QtGui.QApplication.translate("MainWindow", "Volume-ID", None, QtGui.QApplication.UnicodeUTF8))
        self.feat3Label.setText(QtGui.QApplication.translate("MainWindow", "FAT Size", None, QtGui.QApplication.UnicodeUTF8))
        self.feat4Label.setText(QtGui.QApplication.translate("MainWindow", "Number of Fats", None, QtGui.QApplication.UnicodeUTF8))
        self.feat5Label.setText(QtGui.QApplication.translate("MainWindow", "Disk sectors per cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.filesystemLabel.setText(QtGui.QApplication.translate("MainWindow", "File System", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "vfat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "ext2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "ext3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "xfs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Device File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "/dev/sdb", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "/dev/sdb1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "/dev/sdb2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "/dev/sda", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "/dev/sda1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(5, QtGui.QApplication.translate("MainWindow", "/dev/sda2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Formatting.setText(QtGui.QApplication.translate("MainWindow", "Start &Formatting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Formatting.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Formatting.setText(QtGui.QApplication.translate("MainWindow", "&Stop Formatting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Formatting.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_Moony_Creator.setText(QtGui.QApplication.translate("MainWindow", "&About Moony Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_Moony_Creator.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))

import moony_resource_rc
